module.exports = function(grunt) {

  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    concat: {
      options: {
        banner: '/* PEDALPARK.JS - all Backbone.js Models, Views and Routers\n' +
                ' * This file is automatically generated by Grunt,\n' +
                ' * it\'s a concatenation of all source files in src/\n' +
                ' * and should never be directly edited.\n' +
                ' */\n\n' +
                '(function() {\n',
        footer: '}());'
      },
      dist: {
        src: ['pedalpark/static/js/src/startpedalpark.js',
              'pedalpark/static/js/src/models/*.js',
              'pedalpark/static/js/src/views/*.js',
              'pedalpark/static/js/src/routers/*.js'],
        dest: 'pedalpark/static/js/dist/pedalpark.js',
      },
    },
    uglify: {
      my_target: {
        files: {
          'pedalpark/static/js/dist/pedalpark.min.js': ['pedalpark/static/js/dist/pedalpark.js']
        }
      }
    }
  });

  grunt.loadNpmTasks('grunt-contrib-concat');
  grunt.loadNpmTasks('grunt-contrib-uglify');

  grunt.registerTask('default', ['concat','uglify']);

};